# lxpanel
# Autogenerated from man page /usr/share/man/man1/lxpanel.1.gz
complete -c lxpanel -s h -l help -d 'Print help on the options'
complete -c lxpanel -s v -l version -d 'Print the program version'
complete -c lxpanel -s p -l profile -d 'Set the profile to be loaded'

