# xml_pp
# Autogenerated from man page /usr/share/man/man1/xml_pp.1p.gz
complete -c xml_pp -s i -d 'edits the file(s) in place, if an extension is provided (no space between  \\f…'
complete -c xml_pp -s s -d 'the style to use for pretty printing: none, nsgmls, nice, indented, record, o…'
complete -c xml_pp -s p -d 'preserves white spaces in tags'
complete -c xml_pp -s e -d 'use XML::Twig output_encoding (based on Text::Iconv or Unicode::Map8 and  Uni…'
complete -c xml_pp -s l -d 'loads the documents in memory instead of outputting them as they are being pa…'
complete -c xml_pp -s f -d 'read the list of files to process from <file>, one per line'
complete -c xml_pp -s v -d 'verbose (list the current file being processed)'

