# xml_merge
# Autogenerated from man page /usr/share/man/man1/xml_merge.1p.gz
complete -c xml_merge -s o -d 'unless this option is used the program output goes to \\s-1STDOUT\\s0'
complete -c xml_merge -s i -d 'the files use XInclude instead of processing instructions (they were created …'
complete -c xml_merge -s v -d 'verbose output'
complete -c xml_merge -s V -d 'outputs version and exit'
complete -c xml_merge -s h -d 'short help'

