# xml_split
# Autogenerated from man page /usr/share/man/man1/xml_split.1p.gz
complete -c xml_split -s l -d 'level to cut at: 1 generates a file for each child of the root, 2 for each gr…'
complete -c xml_split -s c -d 'generate a file for each element that passes the condition '
complete -c xml_split -s s -d 'generates files of (approximately) <size>'
complete -c xml_split -s g -d 'groups <nb> elements in a single file'
complete -c xml_split -s b -d 'base name for the output, files will be named <base>-<nb><. ext> '
complete -c xml_split -s n -d 'number of digits in the sequence number for each file '
complete -c xml_split -s e -d 'extension to use for generated files '
complete -c xml_split -s i -d 'use XInclude elements instead of Processing Instructions to mark where sub fi…'
complete -c xml_split -s v -d 'verbose output '
complete -c xml_split -s V -d 'outputs version and exit'
complete -c xml_split -s h -d 'short help'

