# xml_spellcheck
# Autogenerated from man page /usr/share/man/man1/xml_spellcheck.1p.gz
complete -c xml_spellcheck -l conf -d 'Gets the options from a configuration file.  \\s-1NOT IMPLEMENTED YET. \\s0'
complete -c xml_spellcheck -l spellchecker -d 'The command to use for spell checking, including any option '
complete -c xml_spellcheck -l backup-extension -d 'By default the original file is saved with a \\f(CW\\*(C`. bak\\*(C\' extension'
complete -c xml_spellcheck -l attributes -d 'Spell check attribute content'
complete -c xml_spellcheck -l exclude_elements -d 'A list of elements that should not be spell checked'
complete -c xml_spellcheck -l include_elements -d 'A list of elements that should be spell checked (by default all elements are …'
complete -c xml_spellcheck -l pretty_print -d 'A pretty print style for the document, as defined in XML::Twig'
complete -c xml_spellcheck -l version -d 'Dislay the tool version and exit'
complete -c xml_spellcheck -l help -d 'Display help message and exit'

