# xmms2-launcher
# Autogenerated from man page /usr/share/man/man1/xmms2-launcher.1.gz
complete -c xmms2-launcher -s l -l logfile -d 'Write log to  file instead of the default log file location'
complete -c xmms2-launcher -s P -l pidfile -d 'Write the pid of  xmms2d (1) to R file '
complete -c xmms2-launcher -s v -l verbose -d 'Make xmms2-launcher verbose'
complete -c xmms2-launcher -s '?' -s h -l help -d 'Show short help information and exit'

