# xmms2d
# Autogenerated from man page /usr/share/man/man1/xmms2d.1.gz
complete -c xmms2d -s v -l verbose -d 'Increase verbosity'
complete -c xmms2d -s q -l quiet -d 'Decrease verbosity'
complete -c xmms2d -s p -l plugindir -d 'Use plugin directory R dir '
complete -c xmms2d -s o -l output -d 'Use output plugin R plugin '
complete -c xmms2d -s i -l ipc-socket -d 'Listen to socket at R url '
complete -c xmms2d -s c -l conf -d 'Use configuration file R file '
complete -c xmms2d -s s -l status-fd -d 'Write to filedescriptor  fd when started'
complete -c xmms2d -l yes-run-as-root -d 'Allow  xmms2d to be run as root. SS Getting help'
complete -c xmms2d -s h -s '?' -l help -d 'Display basic help information and exit'
complete -c xmms2d -s V -l version -d 'Display version information'

